apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.productService.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.productService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.productService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.productService.name }}
    spec:
      containers:
        - name: product-service
          image: "{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}"
          ports:
            - containerPort: {{ .Values.productService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productService.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.productService.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.productService.port }}
